sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.7
    env: TOX_ENV=py37
    sudo: required
    dist: xenial
install:
- pip install tox
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: madedotcom
  password:
    secure: NMIN0dAkF3BIcQMfiVzCkF+x7olmiOVxw9RH99iUWPZufvxLxXJkptHlroA+LQ1sTWt5x4yAPpAID86FCvXSNtreTabdCkvwEU61D9rhEbTbdIwESZ0XzhXrvzrV0VK2T7ahkS1T0F2MWssIT4yj3sk5fa83k0yGxk22XE3GsCAk4boG9j0xiM5KbV55c6WrU/EzsKa6Q8ewYT9XXwEp2EJ3ajikdSjWXv32ahWVtgtoSc2GznzbHxofOcC0HtyeGTnE6kQb/bBUIl5Gu7Y59WO/5h9NZhfU2esXglIf4cM8aYGSc3elORCwZ6wCcgaxUalK/WF0nMKaQpkDqrDemzkza7HxAadSv8ad5MvzmGvz7pm6gXEJKZakqJZ6I1fxp3IfiRsDIF2v1f55vYWQZ6MiZti5fyxNKoIAAx3vG+f8LWrg5G2vV33bAn4hLriM+5/jm+FpaZgsf7WnHsor3qvwhTEZrt/r+wxxocUZ4wCEI+IqxbVvVUfFOysB/HwaQmhIVH2999nI9qIiluTB9AwOPkdVTVu0FgMMDP1AgtdhQFl2bYDrZF3N0cpXlccLrHnLHLQgyZua7MCNVB0IQaGYRYUQsSvWW5+/Q+B2Mu41MG0Kt/kd/PyTMt9fQy+qdsuHiGkAvEL36t717Zif+pUdoj+Zsqk43Vxmy0GktKw=
  on:
    condition: "$TOX_ENV = py37"
