sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.7
    env: TOX_ENV=py37
    sudo: required
    dist: xenial
install:
- pip install tox
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: madedotcom
  password:
    secure: px9eb84zHv77QCR0mY0XFSdm1cSAQAZNgI1M+6URSksiHYBy06sFxMhRPndO8ceBHS+vK6Uo6nVirsF7lUlEj1pZSQ/iJhA9MouGwxfh8H8QDDmGGEm1Q0KIp8LkR5AhWM4mJoXAstts3EjMnCWnFmkjZKGK0h56BWuGs9jwWIejj2S1a6z/a/FDV2MqvbFhVo012prad3ouFGFYeHdQ61cGGIcSOU3iZWxbymHBwwyMbq2K8Ivu1aVdfSALgdJDDW0gWckrwf10K6s2oEBMZex6VHH/ulCunefVmlim4QvHQo/3VVGgAaA88g06a7aYojnqBBN7L7XxfOCj6FJUNdzD54EZ+Yolla1S9TfH1L+QRQ20TUnGm28mA/0KeXMcwWEMa6TcoUzb3tbTz5/J4vaQCzsgl84A7YZWMVjmJGaxNrNxpczvouWxbWkUpOQijdSvOKLSOEQtHJKNW3hc3BYmrljl6VGTQ6d9rUjo/eh1WlbOaG4Ltoo+MdHnC6ztFJEcmc70F6pAOSFzJF1hjXVPkQkFXFNyecrFkHVFF8wC7wz1T4ogLjtLaZ18GIKFZGoh4ynLcRwPddbWw0EuynGmxIg7r6J8FZ5GXxQkk7FU3uhzhNAraLiigICwlac8jSVF032UOWYQ2YK21u1Znw+hw1CqNHeLeAy0PIPHIIU=
