site_name: pytest-contexts
site_description: A plugin to run tests written with the Contexts framework using pytest
site_author: Harry Percival

theme: readthedocs

repo_url: https://github.com/madedotcom/pytest-contexts

pages:
- Home: index.md
